#15
Explicit name set fixes the issue with Require not being able to match the module.
`require.js:900 Error: Mismatched anonymous define() module: undefined`

Implementing this, solves the issue for me.